import type { Todo } from './ITodo';

export const todos: Todo[] = [
  {
    id: 1,
    title: 'Lämna in React-uppgift',
    done: false,
    highImportance: true,
    priority: 1,
    category: 'Skola',
  },
  {
    id: 2,
    title: 'Gå på praktikintervju 1',
    done: true,
    highImportance: true,
    priority: 1,
    category: 'Skola',
  },
  {
    id: 3,
    title: 'Gå på praktikintervju 2',
    done: false,
    highImportance: true,
    priority: 1,
    category: 'Skola',
  },
  {
    id: 4,
    title: 'Gå på praktikintervju 3',
    done: false,
    highImportance: false,
    priority: 1,
    category: 'Skola',
  },
  {
    id: 5,
    title: 'Fastställa praktikplats och skriva papper',
    done: false,
    highImportance: false,
    priority: 1,
    category: 'Skola',
  },
  {
    id: 6,
    title: 'Repetera kursmaterial',
    done: false,
    highImportance: false,
    priority: 1,
    category: 'Skola',
  },
  {
    id: 7,
    title: 'Plantera om inomhusväxter',
    done: false,
    highImportance: false,
    priority: 1,
    category: 'Fritid',
  },
  {
    id: 8,
    title: 'Köpa jeans',
    done: false,
    highImportance: true,
    priority: 1,
    category: 'Fritid',
  },
  {
    id: 9,
    title: 'Städa undan vinterkläder',
    done: false,
    highImportance: false,
    priority: 1,
    category: 'Fritid',
  },
  {
    id: 10,
    title: 'Köpa nya golfbollar och nya handskar',
    done: false,
    highImportance: true,
    priority: 1,
    category: 'Fritid',
  },
];
